Fix protobufClass.toString() cause NoClassDefFoundError or ExceptionInInitializerError (#216)
* Fix protobufClass.toString() cause NoClassDefFoundError